### ISSUE TITLE
Convert Using the Advanced Custom Fields Plugin

### ISSUE THREAD

**Issue by jsmcintyre25** [wptrainingteam/using-the-advanced-custom-fields-plugin#1]
Convert Lesson Plan to GitHub

- [x]  copy and paste from Make site
- [ ]  clean up the Markdown
- [ ]  download the old images
- [ ]  upload the images into GitHub
- [ ]  swap out the image links

**Comment by JulieKuehl** [comment]
https://make.wordpress.org/training/handbook/theme-school/using-the-advanced-custom-fields-plugins/
